version: '3.1'

services:
  asms-app:
    image: 'zaka-web'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certs:/etc/nginx/certs
