export enum StorageKey {
  CURRENT_USER = 'CURRENT_USER',
  AUTH_TOKEN = 'AUTH_TOKEN',
  EXPIRE = 'EXPIRE',
  LANGUAGE = 'LANGUAGE',
  USERNAME = 'USERNAME',
  MOBILE = 'MOBILE',
  PASSWORD = 'PASSWORD',
  USER_ID = 'USER_ID',
  OTP = 'OTP',
  THEME = 'THEME',
  DARK_MODE = 'DARK_MODE',
  LAST_URL = 'LAST_URL',
}
